# Generated by Django 4.1.3 on 2022-11-09 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=258, null=True, unique=True)),
                ('address', models.CharField(max_length=1000)),
                ('current_supply', models.IntegerField(null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('tenure', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('issue_size', models.BigIntegerField(null=True)),
                ('senior_apy', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('junior_apy', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('token_price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('senior_tranche', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('junior_tranche', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_type', models.CharField(max_length=50)),
                ('financing_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('financing_fee', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=25, null=True)),
                ('amount_invested', models.BigIntegerField(default=0)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool', to='mockapi.pool')),
            ],
            options={
                'verbose_name': 'Pool-Asset Map',
                'verbose_name_plural': 'Pool-Asset Maps',
                'unique_together': {('pool', 'asset_name')},
            },
        ),
    ]
